name: qrscanner
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.8.0

dependencies:
  cloud_firestore: ^5.6.12
  cupertino_icons: ^1.0.8
  excel: ^4.0.6
  file_picker: ^10.2.1
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get: 4.7.2
  local_auth: ^2.3.0
  mobile_scanner: ^7.0.1
  open_file: ^3.5.10
  path_provider: ^2.1.5
  pdf: ^3.11.3
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
